resolver: lts-11.6
allow-newer: true
packages:
- '.'
extra-deps:
- rio-0.1.4.0
- vinyl-0.8.1.1
- basic-sop-0.2.0.2
- serialise-0.2.0.0
- cborg-0.2.0.0
- crc-0.1.0.0
- git: git@github.com:matchwood/ixset-typed.git
  commit: 15ddd9eb9a7811c0a1797201de4e52f2ad8dc259
- git: git@github.com:matchwood/lmdb-simple.git
  commit: 637f702aae298ce8000dacb3a1b5e3ac7b0a2664